config.username=user1234
config.message= Hola que tál ñññ
config.listOfValue= hola,que,tál,hoy
config.code= 1234
config.valuesMap={product:'CPU Intel Core i7', description: 'Alder Lake', price: '3000'}